"use client";

import CardBodyCustom from "@/components/comon/custom-table/body";
import { CustomTextField } from "@/components/comon/input/text-field/text-field";
import { zodResolver } from "@hookform/resolvers/zod";
import { Box, Button, Typography } from "@mui/material";
import { useTranslations } from "next-intl";
import { useForm } from "react-hook-form";
import { UserRolesForm, userRolesSchema } from "../schema/create.schema";
import { TablePermissionAdmin } from "../table/table-permission-admin";
import { TablePerimissionEmployee } from "../table/table-permission-employee";
// import TreeTableView from "./table";

export const CreateUserRolesView = () => {
  // const router = useRouter();

  const handleBack = () => {
    // router.push("/pengaturan/access-scorecard-organisasi");
  };
  const userRolesForm = useForm<UserRolesForm>({
    defaultValues: {
      name: "",
      description: null,
      pages: null,
      permissionAdmin: [],
      permissionEmployee: [],
    },
    resolver: zodResolver(userRolesSchema),
  });

  const t = useTranslations("organization.user-roles.create.userRole");

  const { control, handleSubmit } = userRolesForm;

  const onSubmit = async () => {};

  return (
    <CardBodyCustom title={t("title")}>
      <Box
        sx={{
          width: "100%",
          p: 2,
          display: "flex",
          flexDirection: "column",
          gap: 2,
        }}
      >
        <CustomTextField
          control={control}
          name="name"
          label={t("form.name")}
          required
        />
        <CustomTextField
          control={control}
          name="description"
          label={t("form.desc")}
          multiline
          rows={2}
        />
        {/* <StaticAutoComplete
          control={control}
          name="pages"
          label={"Halaman default pasca login"}
          options={transformLevelData(level)}
        /> */}
      </Box>
      <Box
        sx={{
          mt: 1,
          px: 2,
          display: "flex",
          flexDirection: "column",
          // gap: 0.5,
        }}
      >
        <Typography fontWeight={600}>
          {t("form.adminPermission")}{" "}
          <span className="text-red-500">*</span>{" "}
        </Typography>
        <TablePermissionAdmin />
      </Box>
      <Box
        sx={{
          mt: 2,
          px: 2,
          display: "flex",
          flexDirection: "column",
          // gap: 0.5,
        }}
      >
        <Typography fontWeight={600}>
          {t("form.employeePermission")}{" "}
          <span className="text-red-500">*</span>{" "}
        </Typography>
        <TablePerimissionEmployee />
      </Box>
      <Box sx={{ p: 2, display: "flex", justifyContent: "flex-end" }}>
        <Box sx={{ display: "flex", gap: 1 }}>
          <Button onClick={handleBack} variant="outlined">
            Batal
          </Button>
          <Button
            variant="contained"
            sx={{ color: "white" }}
            onClick={handleSubmit(onSubmit)}
          >
            Simpan
          </Button>
        </Box>
      </Box>
    </CardBodyCustom>
  );
};

// const Data = [
//   {
//     Id: 1,
//     ItemId: 1,
//     AdminCategoryId: false,
//     MenuCaption: "Menu Sebagai Admin",
//     ParentLevelId: null,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 2,
//     ItemId: 2,
//     AdminCategoryId: false,
//     MenuCaption: "Dashboard",
//     ParentLevelId: 1,
//     ControllerName: "Admin",
//     ActionName: "MainDashboard",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: "fa fa-dashboard",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard untuk Admin",
//     IsCandidateForRoleLandingPage: true,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 3,
//     ItemId: 3,
//     AdminCategoryId: false,
//     MenuCaption: "Organisasi",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: "fa fa-bank",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 150,
//     ItemId: 1020,
//     AdminCategoryId: false,
//     MenuCaption: "Rekrutmen (admin)",
//     ParentLevelId: 1,
//     ControllerName: "Admin",
//     ActionName: null,
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: "fa fa-user-plus",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 159,
//     ItemId: 1045,
//     AdminCategoryId: false,
//     MenuCaption: "Profil jabatan",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: "fa fa-users",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 15,
//     ItemId: 5,
//     AdminCategoryId: false,
//     MenuCaption: "Pengaturan",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: "fa fa-cogs",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 25,
//     ItemId: 4,
//     AdminCategoryId: false,
//     MenuCaption: "Data Pegawai",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: "fa fa-male",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 125,
//     ItemId: 1000,
//     AdminCategoryId: false,
//     MenuCaption: "Remunerasi",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: "fa fa-money",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 10,
//     ItemId: 6,
//     AdminCategoryId: false,
//     MenuCaption: "Template",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: "fa fa-hospital-o",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 132,
//     ItemId: 1007,
//     AdminCategoryId: false,
//     MenuCaption: "Pembelajaran",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: "fa fa-book",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 175,
//     ItemId: 1073,
//     AdminCategoryId: false,
//     MenuCaption: "Shift Karyawan",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: "fa fa-calendar-check-o",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 27,
//     ItemId: 7,
//     AdminCategoryId: false,
//     MenuCaption: "Perencanaan Kinerja",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: "fa fa-plane",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 29,
//     ItemId: 8,
//     AdminCategoryId: false,
//     MenuCaption: "Evaluasi Kinerja",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 7,
//     ShowThisItem: true,
//     IconClassName: "fa fa-cubes",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 139,
//     ItemId: 2009,
//     AdminCategoryId: false,
//     MenuCaption: "Appoval",
//     ParentLevelId: 1,
//     ControllerName: "Admin",
//     ActionName: null,
//     ItemOrder: 8,
//     ShowThisItem: true,
//     IconClassName: "fa fa-check-square",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 205,
//     ItemId: 1400,
//     AdminCategoryId: false,
//     MenuCaption: "Laporan",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 14,
//     ShowThisItem: true,
//     IconClassName: "fa fa-file",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 178,
//     ItemId: 3002,
//     AdminCategoryId: false,
//     MenuCaption: "Visitasi",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 17,
//     ShowThisItem: true,
//     IconClassName: "fa fa-plane",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 213,
//     ItemId: 1506,
//     AdminCategoryId: false,
//     MenuCaption: "OKR Konfigurasi",
//     ParentLevelId: 1,
//     ControllerName: "Admin",
//     ActionName: null,
//     ItemOrder: 17,
//     ShowThisItem: true,
//     IconClassName: "fa fa-cogs",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 223,
//     ItemId: 1517,
//     AdminCategoryId: false,
//     MenuCaption: "Management Asset",
//     ParentLevelId: 1,
//     ControllerName: "Admin",
//     ActionName: null,
//     ItemOrder: 19,
//     ShowThisItem: true,
//     IconClassName: "fa fa-cogs",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 229,
//     ItemId: 1618,
//     AdminCategoryId: false,
//     MenuCaption: "Talent Map Project",
//     ParentLevelId: 1,
//     ControllerName: "Admin",
//     ActionName: "TalentProject",
//     ItemOrder: 20,
//     ShowThisItem: true,
//     IconClassName: "fa fa-bar-chart",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 230,
//     ItemId: 1701,
//     AdminCategoryId: false,
//     MenuCaption: "Jalur Karir",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 21,
//     ShowThisItem: true,
//     IconClassName: "fa fa-arrow-up",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 234,
//     ItemId: 2200,
//     AdminCategoryId: false,
//     MenuCaption: "Talent Mobility",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 22,
//     ShowThisItem: true,
//     IconClassName: "fa fa-arrow-down",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 241,
//     ItemId: 1800,
//     AdminCategoryId: false,
//     MenuCaption: "Ruang Kerja",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 23,
//     ShowThisItem: true,
//     IconClassName: "fa fa-tasks",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: true,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 251,
//     ItemId: 1900,
//     AdminCategoryId: false,
//     MenuCaption: "Succession Plan",
//     ParentLevelId: 1,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 24,
//     ShowThisItem: true,
//     IconClassName: "fa fa-arrow-right",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: true,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 6,
//     ItemId: 32,
//     AdminCategoryId: false,
//     MenuCaption: "Periode Data Kinerja",
//     ParentLevelId: 3,
//     ControllerName: "Admin",
//     ActionName: "DataPeriod",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 7,
//     ItemId: 33,
//     AdminCategoryId: false,
//     MenuCaption: "Struktur Organisasi",
//     ParentLevelId: 3,
//     ControllerName: "Admin",
//     ActionName: "OrgStructure",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 14,
//     ItemId: 34,
//     AdminCategoryId: false,
//     MenuCaption: "Peran & Akun Pengguna",
//     ParentLevelId: 3,
//     ControllerName: "Admin",
//     ActionName: "RoleAndAccount",
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 9,
//     ItemId: 35,
//     AdminCategoryId: false,
//     MenuCaption: "Berita Umum",
//     ParentLevelId: 3,
//     ControllerName: "Admin",
//     ActionName: "GeneralNews",
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 76,
//     ItemId: 36,
//     AdminCategoryId: false,
//     MenuCaption: "Impor Biodata",
//     ParentLevelId: 3,
//     ControllerName: "Admin",
//     ActionName: "EmpBioImport",
//     ItemOrder: 7,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 11,
//     ItemId: 61,
//     AdminCategoryId: false,
//     MenuCaption: "Kompetensi Inti",
//     ParentLevelId: 10,
//     ControllerName: "Admin",
//     ActionName: "CoreCompetency",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 12,
//     ItemId: 62,
//     AdminCategoryId: false,
//     MenuCaption: "Rencana Kinerja Organisasi",
//     ParentLevelId: 10,
//     ControllerName: "Admin",
//     ActionName: "WorkUnitGoalPlanningTemplate",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 93,
//     ItemId: 63,
//     AdminCategoryId: false,
//     MenuCaption: "Rencana Kinerja Pegawai",
//     ParentLevelId: 10,
//     ControllerName: "Admin",
//     ActionName: "EmployeeGoalPlanningTemplate",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 13,
//     ItemId: 64,
//     AdminCategoryId: false,
//     MenuCaption: "Evaluasi Kinerja Pegawai",
//     ParentLevelId: 10,
//     ControllerName: "Admin",
//     ActionName: "EmployeeGoalEvaluationTemplate",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 16,
//     ItemId: 51,
//     AdminCategoryId: false,
//     MenuCaption: "Kepegawaian Umum",
//     ParentLevelId: 15,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 19,
//     ItemId: 52,
//     AdminCategoryId: false,
//     MenuCaption: "Pondasi Kinerja",
//     ParentLevelId: 15,
//     ControllerName: null,
//     ActionName: null,
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 24,
//     ItemId: 53,
//     AdminCategoryId: false,
//     MenuCaption: "Akses Scorecard Organisasi",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "WUSCAccessRightGroup",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 43,
//     ItemId: 54,
//     AdminCategoryId: false,
//     MenuCaption: "Data Default",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "DefaultEmpField",
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 220,
//     ItemId: 1513,
//     AdminCategoryId: false,
//     MenuCaption: "Approval Level",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "ApprovalLevel",
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 157,
//     ItemId: 9300,
//     AdminCategoryId: false,
//     MenuCaption: "Pengaturan Payroll",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "PayrollSetting",
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 172,
//     ItemId: 2022,
//     AdminCategoryId: false,
//     MenuCaption: "Pengaturan Accurate",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "AkunAccurate",
//     ItemOrder: 7,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 221,
//     ItemId: 1514,
//     AdminCategoryId: false,
//     MenuCaption: "Saldo Klaim",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "ClaimBalance",
//     ItemOrder: 8,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 204,
//     ItemId: 78783,
//     AdminCategoryId: false,
//     MenuCaption: "Penyesuaian Saldo Cuti",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "LeaveBalanceAdjustment",
//     ItemOrder: 9,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 240,
//     ItemId: 78784,
//     AdminCategoryId: false,
//     MenuCaption: "Pengaturan Payroll Lokasi",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "PayrollSettingLocation",
//     ItemOrder: 10,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 246,
//     ItemId: 78785,
//     AdminCategoryId: false,
//     MenuCaption: "Formula Payroll",
//     ParentLevelId: 15,
//     ControllerName: "Admin",
//     ActionName: "PayrollFormula",
//     ItemOrder: 11,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 17,
//     ItemId: 511,
//     AdminCategoryId: false,
//     MenuCaption: "Kategori",
//     ParentLevelId: 16,
//     ControllerName: "EmpSetting",
//     ActionName: "Categories",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 18,
//     ItemId: 512,
//     AdminCategoryId: false,
//     MenuCaption: "Referensi",
//     ParentLevelId: 16,
//     ControllerName: "EmpSetting",
//     ActionName: "Lists",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 171,
//     ItemId: 1062,
//     AdminCategoryId: false,
//     MenuCaption: "Data Master HR",
//     ParentLevelId: 16,
//     ControllerName: "EmpSetting",
//     ActionName: "Hris",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 20,
//     ItemId: 521,
//     AdminCategoryId: false,
//     MenuCaption: "Periode Elemen",
//     ParentLevelId: 19,
//     ControllerName: "Admin",
//     ActionName: "MeasurePeriod",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 22,
//     ItemId: 522,
//     AdminCategoryId: false,
//     MenuCaption: "Tipe Elemen",
//     ParentLevelId: 19,
//     ControllerName: "Admin",
//     ActionName: "MeasureElementType",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 21,
//     ItemId: 523,
//     AdminCategoryId: false,
//     MenuCaption: "Scoring Method",
//     ParentLevelId: 19,
//     ControllerName: "Admin",
//     ActionName: "MeasureValueSetting",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 23,
//     ItemId: 524,
//     AdminCategoryId: false,
//     MenuCaption: "Satuan Ukur",
//     ParentLevelId: 19,
//     ControllerName: "Admin",
//     ActionName: "MeasureUom",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 45,
//     ItemId: 525,
//     AdminCategoryId: false,
//     MenuCaption: "Bobot Penilaian",
//     ParentLevelId: 19,
//     ControllerName: "Admin",
//     ActionName: "PADimensionsWeight",
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 46,
//     ItemId: 526,
//     AdminCategoryId: false,
//     MenuCaption: "Predikat Kinerja",
//     ParentLevelId: 19,
//     ControllerName: "Admin",
//     ActionName: "PAValuePredicate",
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 26,
//     ItemId: 41,
//     AdminCategoryId: false,
//     MenuCaption: "Direktori",
//     ParentLevelId: 25,
//     ControllerName: "Admin",
//     ActionName: "EmployeeDirectory",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 74,
//     ItemId: 71,
//     AdminCategoryId: false,
//     MenuCaption: "Struktur Perencanaan Kustom",
//     ParentLevelId: 27,
//     ControllerName: "Admin",
//     ActionName: "CustomAppraisalStructureForPlanning",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 53,
//     ItemId: 72,
//     AdminCategoryId: false,
//     MenuCaption: "Buka Kunci KPI Organisasi",
//     ParentLevelId: 27,
//     ControllerName: "Admin",
//     ActionName: "WorkUnitGoalPlanningUnlock",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 28,
//     ItemId: 73,
//     AdminCategoryId: false,
//     MenuCaption: "Formulir Hasil Perencanaan",
//     ParentLevelId: 27,
//     ControllerName: "Admin",
//     ActionName: "EmployeeGoalPlanningResult",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 49,
//     ItemId: 74,
//     AdminCategoryId: false,
//     MenuCaption: "Buka Kunci KPI Pegawai",
//     ParentLevelId: 27,
//     ControllerName: "Admin",
//     ActionName: "EmployeeGoalPlanningUnlock",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 109,
//     ItemId: 81,
//     AdminCategoryId: false,
//     MenuCaption: "Formulir Unit Kerja",
//     ParentLevelId: 29,
//     ControllerName: "QueryForReporting",
//     ActionName: "WorkUnitScorecardScoreSummary",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 30,
//     ItemId: 82,
//     AdminCategoryId: false,
//     MenuCaption: "Formulir Pegawai",
//     ParentLevelId: 29,
//     ControllerName: "Admin",
//     ActionName: "EmployeeGoalEvaluationResult",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 110,
//     ItemId: 83,
//     AdminCategoryId: false,
//     MenuCaption: "Rekap Area Pengembangan",
//     ParentLevelId: 29,
//     ControllerName: "QueryForReporting",
//     ActionName: "EmployeeTrainingProgramSummary",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 47,
//     ItemId: 84,
//     AdminCategoryId: false,
//     MenuCaption: "Buka Formulir Terkunci",
//     ParentLevelId: 29,
//     ControllerName: "Admin",
//     ActionName: "EmployeeGoalEvaluationUnlock",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 31,
//     ItemId: 85,
//     AdminCategoryId: false,
//     MenuCaption: "Talent Map",
//     ParentLevelId: 29,
//     ControllerName: "Admin",
//     ActionName: "TalentMap",
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 126,
//     ItemId: 1001,
//     AdminCategoryId: false,
//     MenuCaption: "Daftar Gaji Pegawai",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "EmployeeSalary",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 127,
//     ItemId: 1002,
//     AdminCategoryId: false,
//     MenuCaption: "Pendapatan Tambahan Pegawai",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "EmployeeIncome",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 128,
//     ItemId: 1003,
//     AdminCategoryId: false,
//     MenuCaption: "Potongan Tambahan Pegawai",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "EmployeeDeductable",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 129,
//     ItemId: 1004,
//     AdminCategoryId: false,
//     MenuCaption: "Proses Payroll",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "PayrollProcess",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 130,
//     ItemId: 1005,
//     AdminCategoryId: false,
//     MenuCaption: "Proses PPH21",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "PPH21Process",
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 131,
//     ItemId: 1006,
//     AdminCategoryId: false,
//     MenuCaption: "Proses BPJS",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "BPJSProcess",
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 182,
//     ItemId: 1010,
//     AdminCategoryId: false,
//     MenuCaption: "Terbitkan Pencairan",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "Disbursement",
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 186,
//     ItemId: 10007,
//     AdminCategoryId: false,
//     MenuCaption: "Proses THR",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "EmpHolidayAllowance",
//     ItemOrder: 7,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 187,
//     ItemId: 10008,
//     AdminCategoryId: false,
//     MenuCaption: "Proses Bonus",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "EmpBonusAllowance",
//     ItemOrder: 8,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 247,
//     ItemId: 10009,
//     AdminCategoryId: false,
//     MenuCaption: "Potongan Pinjaman Pegawai",
//     ParentLevelId: 125,
//     ControllerName: "Admin",
//     ActionName: "EmployeeLoan",
//     ItemOrder: 9,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 133,
//     ItemId: 1008,
//     AdminCategoryId: false,
//     MenuCaption: "Riwayat Pembelajaran",
//     ParentLevelId: 132,
//     ControllerName: "Admin",
//     ActionName: "Learning",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 134,
//     ItemId: 1009,
//     AdminCategoryId: false,
//     MenuCaption: "Pantau Pembelajaran Pegawai",
//     ParentLevelId: 132,
//     ControllerName: "Admin",
//     ActionName: "EmpLearning",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 140,
//     ItemId: 2010,
//     AdminCategoryId: false,
//     MenuCaption: "Semua Pengajuan",
//     ParentLevelId: 139,
//     ControllerName: "Admin",
//     ActionName: "HRApprovalMenu",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 151,
//     ItemId: 1021,
//     AdminCategoryId: false,
//     MenuCaption: "Permintaan Tenaga Kerja",
//     ParentLevelId: 150,
//     ControllerName: "Admin",
//     ActionName: "LaborDemand",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 152,
//     ItemId: 1022,
//     AdminCategoryId: false,
//     MenuCaption: "Daftar Calon Karyawan",
//     ParentLevelId: 150,
//     ControllerName: "Admin",
//     ActionName: "ProspectiveEmployee",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 156,
//     ItemId: 1029,
//     AdminCategoryId: false,
//     MenuCaption: "Template PKWT",
//     ParentLevelId: 150,
//     ControllerName: "Admin",
//     ActionName: "PKWTTemplate",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 153,
//     ItemId: 1025,
//     AdminCategoryId: false,
//     MenuCaption: "Generate Pegawai Baru",
//     ParentLevelId: 150,
//     ControllerName: "Admin",
//     ActionName: "GenerateNewEmployee",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 207,
//     ItemId: 1501,
//     AdminCategoryId: false,
//     MenuCaption: "Template Offering Letter",
//     ParentLevelId: 150,
//     ControllerName: "Admin",
//     ActionName: "OfferingLatterTemplate",
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 208,
//     ItemId: 1502,
//     AdminCategoryId: false,
//     MenuCaption: "Template Code Of Conduct",
//     ParentLevelId: 150,
//     ControllerName: "Admin",
//     ActionName: "COCTemplate",
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 162,
//     ItemId: 1048,
//     AdminCategoryId: false,
//     MenuCaption: "Data Induk Profil jabatan",
//     ParentLevelId: 159,
//     ControllerName: "Admin",
//     ActionName: "MainDataOfPositionProfile",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 160,
//     ItemId: 1046,
//     AdminCategoryId: false,
//     MenuCaption: "Kamus Kompetensi",
//     ParentLevelId: 159,
//     ControllerName: "Admin",
//     ActionName: "CompetencyDictionary",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 161,
//     ItemId: 1047,
//     AdminCategoryId: false,
//     MenuCaption: "Profil Kompetensi",
//     ParentLevelId: 159,
//     ControllerName: "Admin",
//     ActionName: "ProfilingCompetency",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 166,
//     ItemId: 1052,
//     AdminCategoryId: false,
//     MenuCaption: "Identifikasi Penilai",
//     ParentLevelId: 159,
//     ControllerName: "Admin",
//     ActionName: "AssessorsIdentificationAdmin",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 250,
//     ItemId: 10053,
//     AdminCategoryId: false,
//     MenuCaption: "Rekap Penilaian Kompetensi",
//     ParentLevelId: 159,
//     ControllerName: "Admin",
//     ActionName: "CompetencyAssessmentReport",
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 176,
//     ItemId: 1074,
//     AdminCategoryId: false,
//     MenuCaption: "Appoval Shift",
//     ParentLevelId: 175,
//     ControllerName: "Admin",
//     ActionName: "ApprovalShiftSubmission",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 209,
//     ItemId: 1503,
//     AdminCategoryId: false,
//     MenuCaption: "Shift Karyawan Detail",
//     ParentLevelId: 175,
//     ControllerName: "Admin",
//     ActionName: "ShiftDetailAll",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 179,
//     ItemId: 1076,
//     AdminCategoryId: false,
//     MenuCaption: "Rekapitulasi Absensi",
//     ParentLevelId: 175,
//     ControllerName: "Admin",
//     ActionName: "AttendanceCalculation",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 185,
//     ItemId: 1077,
//     AdminCategoryId: false,
//     MenuCaption: "Rekapitulasi Lembur",
//     ParentLevelId: 175,
//     ControllerName: "Admin",
//     ActionName: "OvertimeRecapitulation",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 203,
//     ItemId: 78782,
//     AdminCategoryId: false,
//     MenuCaption: "Upload Absen Fingger Print",
//     ParentLevelId: 175,
//     ControllerName: "Admin",
//     ActionName: "UploadAttendanceManual",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 222,
//     ItemId: 1515,
//     AdminCategoryId: false,
//     MenuCaption: "Upload Revisi Lembur",
//     ParentLevelId: 175,
//     ControllerName: "Admin",
//     ActionName: "UploadBulkOvertimeRevition",
//     ItemOrder: 6,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 180,
//     ItemId: 3007,
//     AdminCategoryId: false,
//     MenuCaption: "Data Toko",
//     ParentLevelId: 178,
//     ControllerName: "Admin",
//     ActionName: "StoreData",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 181,
//     ItemId: 3008,
//     AdminCategoryId: false,
//     MenuCaption: "Kunjungan",
//     ParentLevelId: 178,
//     ControllerName: "Admin",
//     ActionName: "VisitationReport",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 183,
//     ItemId: 1011,
//     AdminCategoryId: false,
//     MenuCaption: "Daftar Virtual Account",
//     ParentLevelId: 182,
//     ControllerName: "Admin",
//     ActionName: "VirtualAccount",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: "fa fa-users",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 184,
//     ItemId: 1012,
//     AdminCategoryId: false,
//     MenuCaption: "Daftar Disbursement",
//     ParentLevelId: 182,
//     ControllerName: "Admin",
//     ActionName: "Disbursement",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: "fa fa-money",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 170,
//     ItemId: 1401,
//     AdminCategoryId: false,
//     MenuCaption: "Transaksi Approval",
//     ParentLevelId: 205,
//     ControllerName: "Admin",
//     ActionName: "Reporting",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: "fa fa-file",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 206,
//     ItemId: 1402,
//     AdminCategoryId: false,
//     MenuCaption: "Payroll",
//     ParentLevelId: 205,
//     ControllerName: "Admin",
//     ActionName: "ReportingPayroll",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: "fa fa-file",
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 215,
//     ItemId: 1508,
//     AdminCategoryId: false,
//     MenuCaption: "Organisasi OKR",
//     ParentLevelId: 213,
//     ControllerName: "Admin",
//     ActionName: "OrganizationStructureOKR",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 214,
//     ItemId: 1507,
//     AdminCategoryId: false,
//     MenuCaption: "Periode OKR",
//     ParentLevelId: 213,
//     ControllerName: "Admin",
//     ActionName: "MasterPeriod",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 217,
//     ItemId: 1510,
//     AdminCategoryId: false,
//     MenuCaption: "Batas Warna Pencapaian",
//     ParentLevelId: 213,
//     ControllerName: "Admin",
//     ActionName: "ColorLimitConfiguration",
//     ItemOrder: 4,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 216,
//     ItemId: 1509,
//     AdminCategoryId: false,
//     MenuCaption: "Master Point Aktivitas",
//     ParentLevelId: 213,
//     ControllerName: "Admin",
//     ActionName: "MasterPointActivity",
//     ItemOrder: 5,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 224,
//     ItemId: 1516,
//     AdminCategoryId: false,
//     MenuCaption: "Daftar Asset",
//     ParentLevelId: 223,
//     ControllerName: "Admin",
//     ActionName: "MasterAsset",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 231,
//     ItemId: 1702,
//     AdminCategoryId: false,
//     MenuCaption: "Bangun Jalur Karir",
//     ParentLevelId: 230,
//     ControllerName: "Admin",
//     ActionName: "CareerPathProject",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 232,
//     ItemId: 1703,
//     AdminCategoryId: false,
//     MenuCaption: "Rekap Aspirasi Pegawai",
//     ParentLevelId: 230,
//     ControllerName: "Admin",
//     ActionName: "CareerPathAspiration",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 235,
//     ItemId: 2201,
//     AdminCategoryId: false,
//     MenuCaption: "Master Talent Pool",
//     ParentLevelId: 234,
//     ControllerName: "Admin",
//     ActionName: "TalentPoolMaster",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 236,
//     ItemId: 2202,
//     AdminCategoryId: false,
//     MenuCaption: "Talent Mobility Template",
//     ParentLevelId: 234,
//     ControllerName: "Admin",
//     ActionName: "SuccessionPlanTemplate",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 237,
//     ItemId: 2203,
//     AdminCategoryId: false,
//     MenuCaption: "Talent Mobility Project",
//     ParentLevelId: 234,
//     ControllerName: "Admin",
//     ActionName: "SuccessionPlanProject",
//     ItemOrder: 3,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: null,
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 242,
//     ItemId: 1801,
//     AdminCategoryId: false,
//     MenuCaption: "Pengaturan Ruang Kerja",
//     ParentLevelId: 241,
//     ControllerName: "Admin",
//     ActionName: "WorkSpace",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 244,
//     ItemId: 1803,
//     AdminCategoryId: false,
//     MenuCaption: "Daftar Semua Tugas",
//     ParentLevelId: 241,
//     ControllerName: "Admin",
//     ActionName: "MyTaskListAll",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 252,
//     ItemId: 1902,
//     AdminCategoryId: false,
//     MenuCaption: "Succession Plan Template",
//     ParentLevelId: 251,
//     ControllerName: "Admin",
//     ActionName: "SuccessionPlanFullTemplate",
//     ItemOrder: 1,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
//   {
//     Id: 253,
//     ItemId: 1903,
//     AdminCategoryId: false,
//     MenuCaption: "Succession Plan Project",
//     ParentLevelId: 251,
//     ControllerName: "Admin",
//     ActionName: "SuccessionPlanFullProject",
//     ItemOrder: 2,
//     ShowThisItem: true,
//     IconClassName: null,
//     AllowedAccessToThisItem: false,
//     HasSubItems: false,
//     CandidateForRoleLandingPageCaption: "Dashboard sebagai Admin",
//     IsCandidateForRoleLandingPage: false,
//     MenuCaptionParentLevel: "",
//     AdminCategoryDesc: null,
//     ShowThisItemDesc: null,
//     IsStrategy: false,
//     IsFondation: false,
//     CustomerType: null,
//     IsConsulting: false,
//   },
// ];
