export const dataTable = [
  {
    id: "1000",
    code: "A1B2C3",
    name: "Alpha Watch",
    description: "Elegant wristwatch",
    tahun: 2021,
  },
  {
    id: "1001",
    code: "D4E5F6",
    name: "Titan Sunglasses",
    description: "Stylish sunglasses",
    tahun: 2020,
  },
  {
    id: "1002",
    code: "G7H8I9",
    name: "Nebula Jacket",
    description: "Windproof jacket",
    tahun: 2022,
  },
  {
    id: "1003",
    code: "J1K2L3",
    name: "Echo Headphones",
    description: "Noise-canceling audio",
    tahun: 2023,
  },
  {
    id: "1004",
    code: "M4N5O6",
    name: "Zephyr Sneakers",
    description: "Comfortable running shoes",
    tahun: 2019,
  },
  {
    id: "1005",
    code: "P7Q8R9",
    name: "Storm Backpack",
    description: "Durable travel bag",
    tahun: 2021,
  },
  {
    id: "1006",
    code: "S1T2U3",
    name: "Lunar Phone",
    description: "Latest smartphone",
    tahun: 2024,
  },
  {
    id: "1007",
    code: "V4W5X6",
    name: "Cyber Keyboard",
    description: "Mechanical gaming keyboard",
    tahun: 2020,
  },
  {
    id: "1008",
    code: "Y7Z8A9",
    name: "Velocity Mouse",
    description: "Wireless gaming mouse",
    tahun: 2022,
  },
  {
    id: "1009",
    code: "B1C2D3",
    name: "Quantum Charger",
    description: "Fast charging adapter",
    tahun: 2023,
  },
  {
    id: "1010",
    code: "E4F5G6",
    name: "Blaze T-Shirt",
    description: "Casual cotton t-shirt",
    tahun: 2018,
  },
  {
    id: "1011",
    code: "H7I8J9",
    name: "Nova Wallet",
    description: "Leather wallet",
    tahun: 2021,
  },
  {
    id: "1012",
    code: "K1L2M3",
    name: "Horizon Laptop",
    description: "High-performance laptop",
    tahun: 2024,
  },
  {
    id: "1013",
    code: "N4O5P6",
    name: "Pulse Smartwatch",
    description: "Fitness tracking watch",
    tahun: 2022,
  },
  {
    id: "1014",
    code: "Q7R8S9",
    name: "Summit Hiking Boots",
    description: "Trekking shoes",
    tahun: 2020,
  },
  {
    id: "1015",
    code: "T1U2V3",
    name: "Titanium Bracelet",
    description: "Premium wrist accessory",
    tahun: 2019,
  },
  {
    id: "1016",
    code: "W4X5Y6",
    name: "Glacier Water Bottle",
    description: "Insulated sports bottle",
    tahun: 2021,
  },
  {
    id: "1017",
    code: "Z7A8B9",
    name: "Stratos Duffel Bag",
    description: "Spacious travel bag",
    tahun: 2023,
  },
  {
    id: "1018",
    code: "C1D2E3",
    name: "Orion Desk Lamp",
    description: "Adjustable LED lamp",
    tahun: 2022,
  },
  {
    id: "1019",
    code: "F4G5H6",
    name: "Vertex Gaming Chair",
    description: "Ergonomic chair",
    tahun: 2024,
  },
  {
    id: "1020",
    code: "I7J8K9",
    name: "Solar Power Bank",
    description: "Portable solar charger",
    tahun: 2018,
  },
];
